.zeropage
.globalzp player_vel_x, player_vel_y

.code

.global player_accel
.global player_decel
.global player_accel_left
.global player_accel_right
.global player_decel_left
.global player_decel_right
.global player_limit_vel_neg
.global player_limit_vel_pos
.global player_limit_vel_left
.global player_limit_vel_right
.global player_move_x
.global player_move_y
.global player_wrap_x
.global player_get_screen_coords
.global player_collide_with_grass